### PR TITLE
Removed "Mixed Platforms" and "x86" configs

### PR DESCRIPTION
**Pull request by Benglin**
Hi @pboyer, just minor project/solution tweaks. Please take a look, thanks!

### CODE REVIEW

**Comment by pboyer** [comment]
Lgtm!

**Comment by pboyer** [comment]
Hi @Benglin,  

Do you need me to merge this in?

~Peter

**Comment by pboyer** [comment]
I merged this in, but do you have that ability @Benglin?

**Comment by Benglin** [comment]
Yes I do, @pboyer. Since [you asked me to leave it alone](https://github.com/DynamoDS/GRegClientNET/pull/1#discussion-diff-28517209) before, I thought I should let you see first before screwing things up.

**Pull request merged**
